/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

import Logica.Cuentas;
/**
 *
 * @author Nathan
 */
public class Proyecto2_1 extends javax.swing.JFrame {

    private Cuentas cuentas;
  
   
    public Proyecto2_1() {
        initComponents();
        this.cuentas = new Cuentas();  
        setSize(750, 800);
        setLocationRelativeTo(null);
        setResizable(false);
    }
        
    public Proyecto2_1(Cuentas registro) {
        initComponents(); 
        setSize(750, 800);
        this.cuentas = registro;
        setLocationRelativeTo(null);
        setResizable(false);
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Iniciosesion = new javax.swing.JButton();
        Crearcuenta = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        registro = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        Iniciosesion.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        Iniciosesion.setText("Inicio Sesión");
        Iniciosesion.setToolTipText("");
        Iniciosesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Iniciosesion.setOpaque(true);
        Iniciosesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciosesionActionPerformed(evt);
            }
        });
        getContentPane().add(Iniciosesion);
        Iniciosesion.setBounds(240, 240, 270, 80);

        Crearcuenta.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        Crearcuenta.setText("Crear Cuenta");
        Crearcuenta.setToolTipText("");
        Crearcuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Crearcuenta.setOpaque(true);
        Crearcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearcuentaActionPerformed(evt);
            }
        });
        getContentPane().add(Crearcuenta);
        Crearcuenta.setBounds(240, 370, 270, 80);

        Salir.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        Salir.setText("Salir");
        Salir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Salir.setOpaque(true);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir);
        Salir.setBounds(240, 510, 270, 80);

        jPanel1.setOpaque(false);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 220, 350, 380);

        registro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stra.png"))); // NOI18N
        registro.setToolTipText("");
        registro.setFocusable(false);
        getContentPane().add(registro);
        registro.setBounds(0, 0, 760, 860);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciosesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciosesionActionPerformed
        // TODO add your handling code here:
        new Registro(this.cuentas).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_IniciosesionActionPerformed

    private void CrearcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearcuentaActionPerformed
        // TODO add your handling code here:
        new Crearcuenta(this.cuentas).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CrearcuentaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto2_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto2_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto2_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto2_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyecto2_1().setVisible(true);
            }
        });

    }

    public static void panel(String[] args) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Crearcuenta;
    private javax.swing.JButton Iniciosesion;
    private javax.swing.JButton Salir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel registro;
    // End of variables declaration//GEN-END:variables
}
